# Generated by Django 4.2.13 on 2024-05-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
