# Generated by Django 4.2.13 on 2024-05-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_pets_pet_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pets',
            options={'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
