# Generated by Django 4.2.13 on 2024-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_pets_options_alter_pets_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
