# Generated by Django 4.2.13 on 2024-05-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_pets_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='health',
            field=models.TextField(null=True),
        ),
    ]
