# Generated by Django 4.2.13 on 2024-06-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.pets'),
        ),
    ]
