# Generated by Django 4.2.13 on 2024-06-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_volunteer_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Adopt',
        ),
    ]
